//Student's Full Name- Tasfique Enam
//Student's ID- J16020825/5886429
//Modification Date 20/06/2019
//Purpose: It is the main Frame
package assignment3;

import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

/**
 *
 * @author Tasfi
 */
public class Frame extends javax.swing.JFrame {

    private ArrayList<Laptop> laptopArrayList = new ArrayList<>(); //arraylist  for keeping laptop object.
    private ArrayList<Sales> salesArrayList = new ArrayList<>(); //for keeping sales object
    Laptop laptopObject; //laptop object 
    Sales salesObject; //sales Object
    private Sales salesDisplayObject; //object for sales.
    private int[] stock = {2,3,4}; // array for keeping laptop stocks.
    
    boolean check; //used for validation.
    
     private static String[] laptopPictures = {null, "ASUS.jpg", "Lenovo.jpg", "MSI.jpg"}; //array for keeping laptop images.
     private final Icon[] icons = {null,
         new ImageIcon(getClass().getResource(laptopPictures[1])),
         new ImageIcon(getClass().getResource(laptopPictures[2])),
         new ImageIcon(getClass().getResource(laptopPictures[3])),
         
     };
    
    public Frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        Title = new javax.swing.JLabel();
        labelBrandModel = new javax.swing.JLabel();
        labelCPU = new javax.swing.JLabel();
        labelRAM = new javax.swing.JLabel();
        labelScreenSize = new javax.swing.JLabel();
        labelColor = new javax.swing.JLabel();
        comboBoxBrandModel = new javax.swing.JComboBox<>();
        comboBoxCPU = new javax.swing.JComboBox<>();
        fourGB = new javax.swing.JRadioButton();
        eightGB = new javax.swing.JRadioButton();
        sixteenGB = new javax.swing.JRadioButton();
        fourteenInch = new javax.swing.JRadioButton();
        fifteenInch = new javax.swing.JRadioButton();
        textFieldColor = new javax.swing.JTextField();
        labelAdditionalItems = new javax.swing.JLabel();
        checkTouchScreen = new javax.swing.JCheckBox();
        checkAddFour = new javax.swing.JCheckBox();
        checkAntiVirus = new javax.swing.JCheckBox();
        checkBag = new javax.swing.JCheckBox();
        checkOffice = new javax.swing.JCheckBox();
        buttonPayment = new javax.swing.JButton();
        buttonSave = new javax.swing.JButton();
        buttonQuit = new javax.swing.JButton();
        buttonDisplay = new javax.swing.JButton();
        labelImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));

        Title.setFont(new java.awt.Font("Lucida Calligraphy", 3, 24)); // NOI18N
        Title.setText("Day Day Computers");

        labelBrandModel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        labelBrandModel.setText("Brand & Model");

        labelCPU.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        labelCPU.setText("CPU");

        labelRAM.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        labelRAM.setText("RAM");

        labelScreenSize.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        labelScreenSize.setText("Screen Size");

        labelColor.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        labelColor.setText("Color");

        comboBoxBrandModel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "ASUS - Zenbook Pro", "Lenovo - ThinkPad Carbon", "MSI - GP62 Leopard Pro" }));
        comboBoxBrandModel.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboBoxBrandModelItemStateChanged(evt);
            }
        });
        comboBoxBrandModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxBrandModelActionPerformed(evt);
            }
        });

        comboBoxCPU.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Core i3", "Core i5", "Core i7" }));

        buttonGroup1.add(fourGB);
        fourGB.setSelected(true);
        fourGB.setText("4GB");
        fourGB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourGBActionPerformed(evt);
            }
        });

        buttonGroup1.add(eightGB);
        eightGB.setText("8GB");

        buttonGroup1.add(sixteenGB);
        sixteenGB.setText("16GB");

        buttonGroup2.add(fourteenInch);
        fourteenInch.setSelected(true);
        fourteenInch.setText("14\"");

        buttonGroup2.add(fifteenInch);
        fifteenInch.setText("15.6\"");

        labelAdditionalItems.setFont(new java.awt.Font("Ebrima", 1, 16)); // NOI18N
        labelAdditionalItems.setText("Additional Items: ");

        checkTouchScreen.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        checkTouchScreen.setText("Touch Screen");
        checkTouchScreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkTouchScreenActionPerformed(evt);
            }
        });

        checkAddFour.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        checkAddFour.setText("Additional 4GB RAM");
        checkAddFour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkAddFourActionPerformed(evt);
            }
        });

        checkAntiVirus.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        checkAntiVirus.setText("AntiVirus Software");
        checkAntiVirus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkAntiVirusActionPerformed(evt);
            }
        });

        checkBag.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        checkBag.setText("Laptop bag");

        checkOffice.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        checkOffice.setText("Office Included");
        checkOffice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkOfficeActionPerformed(evt);
            }
        });

        buttonPayment.setBackground(new java.awt.Color(255, 0, 0));
        buttonPayment.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        buttonPayment.setText("Payment");
        buttonPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPaymentActionPerformed(evt);
            }
        });

        buttonSave.setBackground(new java.awt.Color(255, 0, 0));
        buttonSave.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        buttonSave.setText("Save");
        buttonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaveActionPerformed(evt);
            }
        });

        buttonQuit.setBackground(new java.awt.Color(255, 0, 0));
        buttonQuit.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        buttonQuit.setText("Quit");
        buttonQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonQuitActionPerformed(evt);
            }
        });

        buttonDisplay.setBackground(new java.awt.Color(255, 0, 0));
        buttonDisplay.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        buttonDisplay.setText("Display Sales");
        buttonDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDisplayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(buttonPayment)
                .addGap(101, 101, 101)
                .addComponent(buttonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(buttonDisplay)
                .addGap(90, 90, 90)
                .addComponent(buttonQuit, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkTouchScreen)
                            .addComponent(checkAddFour)
                            .addComponent(labelAdditionalItems)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(178, 178, 178)
                                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(219, 219, 219))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(labelColor)
                                        .addComponent(labelScreenSize)
                                        .addComponent(labelCPU)
                                        .addComponent(labelRAM)
                                        .addComponent(labelBrandModel))
                                    .addGap(85, 85, 85)
                                    .addComponent(fourteenInch))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(checkBag, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(116, 116, 116)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(checkOffice, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(checkAntiVirus))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(178, 178, 178)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(comboBoxBrandModel, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comboBoxCPU, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fifteenInch)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(fourGB)
                                        .addGap(18, 18, 18)
                                        .addComponent(eightGB)
                                        .addGap(18, 18, 18)
                                        .addComponent(sixteenGB))
                                    .addComponent(textFieldColor, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelImage, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelBrandModel)
                            .addComponent(comboBoxBrandModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelCPU)
                            .addComponent(comboBoxCPU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelRAM)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(fourGB)
                                .addComponent(eightGB)
                                .addComponent(sixteenGB)))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelScreenSize)
                            .addComponent(fourteenInch)
                            .addComponent(fifteenInch))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelColor)
                            .addComponent(textFieldColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(labelImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addComponent(checkTouchScreen)
                .addGap(28, 28, 28)
                .addComponent(labelAdditionalItems)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkAddFour)
                    .addComponent(checkAntiVirus))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkBag)
                    .addComponent(checkOffice))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonQuit, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxBrandModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxBrandModelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxBrandModelActionPerformed

    private void fourGBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourGBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fourGBActionPerformed

    private void checkTouchScreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkTouchScreenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkTouchScreenActionPerformed

    private void checkOfficeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkOfficeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkOfficeActionPerformed

    private void buttonPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPaymentActionPerformed
        // method for payment button.
        if(comboBoxBrandModel.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Brand and Model haven't been Selected. "); //validation for if brand and model haven't been selected and the user clicks payment button    
        }
        else if (stock[comboBoxBrandModel.getSelectedIndex()-1] == 0){ //when the array list runs out of laptop stock for a specific model and it minisus 1.
            JOptionPane.showMessageDialog(null, "Stock is finished for this Laptop ");
        }
        else if(comboBoxCPU.getSelectedIndex() == 0) { //if the user doesn't select CPU when clicking payment.
            JOptionPane.showMessageDialog(null, "CPU haven't been Selected. ");    
        }
        else if(!(textFieldColor.getText().equalsIgnoreCase("silver") || textFieldColor.getText().equalsIgnoreCase("red") || textFieldColor.getText().equalsIgnoreCase("black"))) {
            JOptionPane.showMessageDialog(null, "You have inputted the Wrong Color or The Color Field is empty. "); //if the user input wrong colour or colour field.
        }
        else {
            
            laptopObject = new Laptop(); //creating a new laptop object
            
            
            laptopObject.setColor(textFieldColor.getText());
            //validation if the user have selected everything before proceeding to the next step.
            if(comboBoxBrandModel.getSelectedIndex() == 1) {
                laptopObject.setLaptopBrandModel("ASUS - ZenBook Pro");
            }
            else if(comboBoxBrandModel.getSelectedIndex() == 2) {
                 laptopObject.setLaptopBrandModel("Lenovo - ThinkPad Carbon");
            }
            else if(comboBoxBrandModel.getSelectedIndex() == 3) {
                 laptopObject.setLaptopBrandModel("MSI - GP62 Leopard Pro");
            }

            if(comboBoxCPU.getSelectedIndex() == 1) {
                laptopObject.setCPU("Core i3");
            }
            else if(comboBoxCPU.getSelectedIndex() == 2) {
                laptopObject.setCPU("Core i5");
            }
            else if(comboBoxCPU.getSelectedIndex() == 3) {
                laptopObject.setCPU("Core i7");
            }
            if(fourGB.isSelected()) {
                laptopObject.setRAM("4GB");
                }
            if(eightGB.isSelected()) {
                laptopObject.setRAM("8GB");
                }
            if(sixteenGB.isSelected()) {
                laptopObject.setRAM("16GB");
                }

            if(fourteenInch.isSelected()) {
                laptopObject.setScreenSize("14 Inch");
                }
            if(fifteenInch.isSelected()) {
                laptopObject.setScreenSize("15 Inch");
                }
            if(checkTouchScreen.isSelected()) {
                laptopObject.setTouchScreen(true);
            }
            if(checkAddFour.isSelected()) {
                laptopObject.setAddRAM(true); 
            }
            if(checkAntiVirus.isSelected()) {
                laptopObject.setAntivirus(true); 
            }
            if(checkBag.isSelected()) {
                laptopObject.setBag(true); 
            }
            if(checkOffice.isSelected()) {
                laptopObject.setOffice(true); 
                            
        }
        check = true; //used for validation
        salesDisplayObject = new Sales(laptopObject); // to make frame visible, object was created for it.
        salesDisplayObject.setVisible(true);
        salesDisplayObject.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        stock[comboBoxBrandModel.getSelectedIndex()-1]--; //for stock
        
        }
    
    }//GEN-LAST:event_buttonPaymentActionPerformed

    private void checkAddFourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkAddFourActionPerformed
        // TODO add your handling code here: don't know what this code is for 
    }//GEN-LAST:event_checkAddFourActionPerformed

    private void comboBoxBrandModelItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboBoxBrandModelItemStateChanged
         if (comboBoxBrandModel.getSelectedIndex() == 0) { //codes used for the combo for for the laptops.
            labelImage.setIcon(null);
        } else if (comboBoxBrandModel.getSelectedIndex() == 1) {
            labelImage.setIcon(icons[1]);
        } else if (comboBoxBrandModel.getSelectedIndex() == 2) {
            labelImage.setIcon(icons[2]);
            
        } else if (comboBoxBrandModel.getSelectedIndex() == 3) {
            labelImage.setIcon(icons[3]);
            
        }
            
    }//GEN-LAST:event_comboBoxBrandModelItemStateChanged

    private void buttonQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonQuitActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Thank You for using the Programme. ");
        System.exit(0); //for exiting the programme 
        
    }//GEN-LAST:event_buttonQuitActionPerformed

    private void buttonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveActionPerformed

        if(check == false) {
             JOptionPane.showMessageDialog(null, "You cannot Save, Please Make Payment First. "); // not allowing the user to save, before making the payment.
        } 
        else {
            if (salesDisplayObject.isDisplayable()) //for display purpose of the new sale JoptionPane
                check = false;
            else {
            //codes below are for validation purpose... there are lot of validation -_-
            if(comboBoxBrandModel.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog(null, "Brand and Model haven't been Selected. ");    
            }
            else if(comboBoxCPU.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog(null, "CPU haven't been Selected. ");    
            }
            else if(!(textFieldColor.getText().equalsIgnoreCase("silver") || textFieldColor.getText().equalsIgnoreCase("red") || textFieldColor.getText().equalsIgnoreCase("black"))) {
                JOptionPane.showMessageDialog(null, "You have inputted the Wrong Color or The Color Field is empty. ");
            }
            else {

                laptopObject = new Laptop(); //creating a new laptop object.

                laptopObject.setColor(textFieldColor.getText());
                
                //these codes below are to check if the user have selected the laptop specs before proceeding to the next process.
                if(comboBoxBrandModel.getSelectedIndex() == 1) {
                    laptopObject.setLaptopBrandModel("ASUS - ZenBook Pro");
                }
                else if(comboBoxBrandModel.getSelectedIndex() == 2) {
                     laptopObject.setLaptopBrandModel("Lenovo - ThinkPad Carbon");
                }
                else if(comboBoxBrandModel.getSelectedIndex() == 3) {
                     laptopObject.setLaptopBrandModel("MSI - GP62 Leopard Pro");
                }

                if(comboBoxCPU.getSelectedIndex() == 1) {
                    laptopObject.setCPU("Core i3");
                }
                else if(comboBoxCPU.getSelectedIndex() == 2) {
                    laptopObject.setCPU("Core i5");
                }
                else if(comboBoxCPU.getSelectedIndex() == 3) {
                    laptopObject.setCPU("Core i7");
                }
                if(fourGB.isSelected()) {
                    laptopObject.setRAM("4GB");
                    }
                if(eightGB.isSelected()) {
                    laptopObject.setRAM("8GB");
                    }
                if(sixteenGB.isSelected()) {
                    laptopObject.setRAM("16GB");
                    }

                if(fourteenInch.isSelected()) {
                    laptopObject.setScreenSize("14 Inch");
                    }
                if(fifteenInch.isSelected()) {
                    laptopObject.setScreenSize("15 Inch");
                    }
                if(checkTouchScreen.isSelected()) {
                    laptopObject.setTouchScreen(true);
                }
                if(checkAddFour.isSelected()) {
                    laptopObject.setAddRAM(true); 
                }
                if(checkAntiVirus.isSelected()) {
                    laptopObject.setAntivirus(true); 
                }
                if(checkBag.isSelected()) {
                    laptopObject.setBag(true); 
                }
                if(checkOffice.isSelected()) {
                    laptopObject.setOffice(true);
                }
                
            laptopArrayList.add(laptopObject); //adding laptop object to arraylist of laptop
            salesArrayList.add(salesDisplayObject); //adding sales display object to the array list.
            
            check = false;
            JOptionPane.showMessageDialog(null, "Your Selected Laptop have been saved. ");
            }
            }
            
        }

    }//GEN-LAST:event_buttonSaveActionPerformed

    private void buttonDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDisplayActionPerformed
        // TODO add your handling code here:
        try {
            String str ="" ;
            for(int x=0; x<salesArrayList.size(); x++) { //display all the values from the to String method that was created in Laptop class and Sales class, check those class to see the to String methods.
                str += laptopArrayList.get(x).toString() + salesArrayList.get(x).toString();
            }
            JTextArea textArea = new JTextArea(str);
            JScrollPane scrollPane = new JScrollPane(textArea);  
            textArea.setLineWrap(true);  
            textArea.setWrapStyleWord(true); 
            scrollPane.setPreferredSize( new Dimension( 500, 500 ) );
            JOptionPane.showMessageDialog(null, scrollPane, "Day Day Computer's Sale", JOptionPane.YES_NO_OPTION);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,  "You have clicked Payment Twice. Restart the Programme Again ");
        }
     
        
        
    }//GEN-LAST:event_buttonDisplayActionPerformed

    private void checkAntiVirusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkAntiVirusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkAntiVirusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    private javax.swing.JButton buttonDisplay;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton buttonPayment;
    private javax.swing.JButton buttonQuit;
    private javax.swing.JButton buttonSave;
    private javax.swing.JCheckBox checkAddFour;
    private javax.swing.JCheckBox checkAntiVirus;
    private javax.swing.JCheckBox checkBag;
    private javax.swing.JCheckBox checkOffice;
    private javax.swing.JCheckBox checkTouchScreen;
    private javax.swing.JComboBox<String> comboBoxBrandModel;
    private javax.swing.JComboBox<String> comboBoxCPU;
    private javax.swing.JRadioButton eightGB;
    private javax.swing.JRadioButton fifteenInch;
    private javax.swing.JRadioButton fourGB;
    private javax.swing.JRadioButton fourteenInch;
    private javax.swing.JLabel labelAdditionalItems;
    private javax.swing.JLabel labelBrandModel;
    private javax.swing.JLabel labelCPU;
    private javax.swing.JLabel labelColor;
    private javax.swing.JLabel labelImage;
    private javax.swing.JLabel labelRAM;
    private javax.swing.JLabel labelScreenSize;
    private javax.swing.JRadioButton sixteenGB;
    private javax.swing.JTextField textFieldColor;
    // End of variables declaration//GEN-END:variables
}
