//Student's Full Name- Tasfique Enam
//Student's ID- J16020825/5886429
//Modification Date 20/06/2019
//Purpose: It is the Sales Class.
package assignment3;

import javax.swing.JOptionPane;

public class Sales extends javax.swing.JFrame {

    private Laptop laptopObject = new Laptop();
    private Frame frameObject = new Frame();
    //boolean check = frameObject.check;
    /**
     * Creates new form Sales
     */
    public Sales(Laptop laptopObject) { 
        this.laptopObject.equalTo(laptopObject); //the method that was used in the Laptop class called "equalTo"
        initComponents();
        textArea.setText(laptopObject.toString()); //The text area, where the laptop details show.
        textFieldTotalPrice.setText(this.laptopObject.laptopCalculation()+""); //for total Price of the laptop
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTotalPrice = new javax.swing.JLabel();
        labelDiscount = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        textFieldTotalPrice = new javax.swing.JTextField();
        textFieldDiscount = new javax.swing.JTextField();
        textPriceAfterDiscount = new javax.swing.JTextField();
        textFieldPayment = new javax.swing.JTextField();
        textFieldBalance = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelTotalPrice.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        labelTotalPrice.setText("Total Price");

        labelDiscount.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        labelDiscount.setText("Discount");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel3.setText("Payment");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel4.setText("Price After Discount");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel5.setText("Balance");

        textFieldTotalPrice.setEditable(false);
        textFieldTotalPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldTotalPriceActionPerformed(evt);
            }
        });

        textFieldDiscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldDiscountActionPerformed(evt);
            }
        });

        textPriceAfterDiscount.setEditable(false);

        textFieldPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldPaymentActionPerformed(evt);
            }
        });

        textFieldBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldBalanceActionPerformed(evt);
            }
        });

        textArea.setEditable(false);
        textArea.setColumns(20);
        textArea.setRows(5);
        jScrollPane1.setViewportView(textArea);

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 12, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelDiscount)
                                    .addComponent(jLabel4))
                                .addGap(24, 24, 24))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5))
                                .addGap(27, 27, 27)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textPriceAfterDiscount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldDiscount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(textFieldPayment)
                                .addComponent(textFieldBalance, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE))
                            .addComponent(textFieldTotalPrice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelTotalPrice)
                            .addComponent(textFieldTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textFieldDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelDiscount))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textPriceAfterDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(textFieldPayment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(textFieldBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(backButton, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldTotalPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldTotalPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldTotalPriceActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        boolean dispose = false;
        try {
            if(Double.parseDouble(textFieldPayment.getText()) >= 0) { //these codes are used for validation purpose. 
                dispose = true;
                if (textFieldBalance.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Please click enter to proceed");
                    dispose = false;
                }
                else
                    dispose = true;
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "You can't click back without inputting Payment ");
            dispose = false;
        }

        
        if (dispose) {
            dispose();
        }
           
    

    }//GEN-LAST:event_backButtonActionPerformed

    private void textFieldBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldBalanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldBalanceActionPerformed

    private void textFieldDiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldDiscountActionPerformed
        //validation of the dicount text field, the text field can't be over 100 or below 1... as the dicount is calculated in percentage.
        try {
            if(Double.parseDouble(textFieldDiscount.getText()) >= 1 && Double.parseDouble(textFieldDiscount.getText()) <= 100) {
            try {
            laptopObject.setDiscountRate(Double.parseDouble(textFieldDiscount.getText()));
            } catch (Exception e) {

            }
            laptopObject.Discount();
            textPriceAfterDiscount.setText(laptopObject.getPriceAfterDiscount()+"");
            
            } else {
                JOptionPane.showMessageDialog(null, "You have inputted Discount Percentage Below 1 or Above 100 ");         
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Invalid Input ");           
        }
        
        
    }//GEN-LAST:event_textFieldDiscountActionPerformed

    private void textFieldPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldPaymentActionPerformed
        try { // try catch block
           //validation so that the the payment is greater or equal to the cost price...
            if((Double.parseDouble(textFieldPayment.getText()) >= Double.parseDouble(textFieldTotalPrice.getText())) || (Double.parseDouble(textFieldPayment.getText()) >= Double.parseDouble(textPriceAfterDiscount.getText())))  { //validation if the user inputted the right input
                try {
                laptopObject.setPayment(Double.parseDouble(textFieldPayment.getText()));          
                } catch (Exception e) {

                }
                laptopObject.Balance();
                textFieldBalance.setText(laptopObject.Balance()+"");
            } else {
                JOptionPane.showMessageDialog(null, "Not enough Money to make the Payment "); //error message if the user inputs payments less than the total.
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Invalid Input ");
        }
        
        
    }//GEN-LAST:event_textFieldPaymentActionPerformed

    public String toString() { //to string to display the laptop cost of the specific model.
       String str = "Total Price RM: "+textFieldTotalPrice.getText() + "\n"+
               "Discount %: "+textFieldDiscount.getText() + "\n"+
               "Price After Discount RM: "+textPriceAfterDiscount.getText() + "\n"+
               "Payment RM: "+textFieldPayment.getText() + "\n" +
               "Balance RM: "+textFieldBalance.getText() + "\n" ;
        
        return str;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelDiscount;
    private javax.swing.JLabel labelTotalPrice;
    private javax.swing.JTextArea textArea;
    private javax.swing.JTextField textFieldBalance;
    private javax.swing.JTextField textFieldDiscount;
    private javax.swing.JTextField textFieldPayment;
    private javax.swing.JTextField textFieldTotalPrice;
    private javax.swing.JTextField textPriceAfterDiscount;
    // End of variables declaration//GEN-END:variables
}
